### ISSUE TITLE
Undefined is not an object...

### ISSUE THREAD

**Issue by bsdt-snelson** [angelos3lex/react-native-smtp-mailer#1]
After following all installation procedures for Android I get : TypeError: undefined is not an object (evaluating '_reactNativeSmtpMailer2.default.sendMail')

I tried a number of different smtp relays I have access to and they all returned the same error... perhaps an installation issue?

**Comment by bsdt-snelson** [comment]
Yes, the manual installation process was followed.  Here is my code:

import React, {Component} from 'react';
import {Container, Content, Text} from 'native-base';
import {Alert} from 'react-native';
import myPerms from '../json/myPerms.json';
import containerPerms from '../json/containers.json';
import {ReactNativeAD, ADLoginView} from 'react-native-azure-ad'
import RNSmtpMailer from 'react-native-smtp-mailer';
…..
RNSmtpMailer.sendMail({
            mailhost: "smtp.gmail.com",
            port: "465",
            ssl: true, //if ssl: false, TLS is enabled,**note:** in iOS TLS/SSL is determined automatically, so either true or false is the same
            username: "xxxs@gmail.com",
            password: "mypasswordhere",
        from: "xxxx@yyyy.com",
        recipients: " xxxx@yyyy.com ",
        subject: "test smtp",
        htmlBody: "<h1>header</h1><p>body</p>",
        })
        .then(success => console.log("EMAIL SENT: " + success))
        .catch(err => console.log("EMAIL ERROR: " + err));

I did modify the android\build.gradle file as such:
dependencies {
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile fileTree(dir: "libs", include: ["*.jar"])
}

And I am running react-native version 0.55.4

**Comment by angelos3lex** [comment]
your android/settings.gradle should contain:
```
...
include ':react-native-smtp-mailer'
project(':react-native-smtp-mailer').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-smtp-mailer/android')
```

your **android/app/build.gradle** should contain: //**Not** android/build.gradle as you mentioned
```
dependencies {
    implementation project(':react-native-smtp-mailer')
    implementation fileTree(dir: "libs", include: ["*.jar"])
... //everything else
}
```
And in MainApplication.java, import and package:
```
import com.reactlibrary.RNSmtpMailerPackage;
...
 new RNSmtpMailerPackage() // in getPackage() list
```

**Comment by bsdt-snelson** [comment]
“And in MainApplication.java, import and package:

import com.reactlibrary.RNSmtpMailerPackage;

...

 new RNSmtpMailerPackage() // in getPackage() list
“

Helped as I don’t believe that code in the documentation on the Github page- if it is I missed it.

However, there is now another error:  “ReferenceError: Can't find variable: RNFS” likely due to the fact that RNFS used in the attachmentPaths property is not defined in the documentation.  Once it is defined it works fine.

Thanks!
Shawn

**Comment by angelos3lex** [comment]
@bsdt-snelson It's the first step in manual installation of Android.
Yeah, RNFS is from [react-native-fs](https://github.com/itinance/react-native-fs) library, and it is used in documentation just to show a way of accessing files in the phone, it is not necessary.
Glad that it worked!

**Comment by ahtesham-shah** [comment]
when i calls a method by clicking button it directly gives red coloured error sendMail is not defined

**Comment by shuffledex** [comment]
same error here
