### ISSUE TITLE
Couldn't Connect to SMTP host

### ISSUE THREAD

**Issue by carizzapanopio** [angelos3lex/react-native-smtp-mailer#11]
Hi. I am hoping you could help me. I can't seem to send an email even though I followed all the steps. I keep on getting this error:

![image](https://user-images.githubusercontent.com/3467685/58790021-17557f80-8622-11e9-86ff-c1c8a0abbda0.png)

**Comment by angelos3lex** [comment]
Hi @carizzapanopio  , please make sure that in your Gmail, you have activated the use of less secure apps.
