### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by truckhiem** [angelos3lex/react-native-smtp-mailer#12]
Hi great to have your code to send email but I have this issue when trying to integrate:

`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Your sample work very well but when I integrate to my project this issue come up. 
I tried many time and find out that this issue happen after I install pod with "pod 'mailcore2-ios'"

Could you please to help. Thanks

**Comment by angelos3lex** [comment]
@truckhiem Have you resolved it yet? If not, do you want to add your RN version, or even better provide a sample repo where this is reproducable?
