### ISSUE TITLE
a stable connection to the server could not be established

### ISSUE THREAD

**Issue by HariHipot** [angelos3lex/react-native-smtp-mailer#13]
I trying to send email in iPad. i have done the complete procedure as well. but receive this error.
I'm using office365 SMTP port with my personal email id.

**Comment by HariHipot** [comment]
I got answer Guys.
I have changed Auth type as MCOAuthTypeSASLLogin and connectionType as MCOConnectionTypeStartTLS

**Comment by SainagChunduru** [comment]
Hey @HariHipot, I am also facing the same error.

Could you help me with how you have solved this? And where you have updated AuthType and connectionType.

**Comment by laraferroni** [comment]
Changing these worked for me. You can set these in RNSmtpMailer.m:
https://github.com/angelos3lex/react-native-smtp-mailer/blob/87dcac3b1e98efee0c2a8bad8a030b5a25989711/ios/RNSmtpMailer.m#L41
