### ISSUE TITLE
 Error: Could not connect to SMTP host

### ISSUE THREAD

**Issue by sauravjmt** [angelos3lex/react-native-smtp-mailer#14]
Hi ,

i am getting following error in Android 

 { [
    Error: Could not connect to SMTP host: smtp.gmail.com, port: 465, response: -1]
   framesToPop: 1,
   nativeStackAndroid: [],
   userInfo: null,
   code: 'EUNSPECIFIED',
   line: 2108,
   column: 26,
   sourceURL: 'http://localhost:8081/index.delta?platform=android&dev=true&minify=false' }

**Comment by angelos3lex** [comment]
Hi @sauravjmt , please make sure that in your Gmail, you have activated the use of less secure apps.
