### ISSUE TITLE
RNSmtpMailer.podspec is missing homepage attribute

### ISSUE THREAD

**Issue by denunv** [angelos3lex/react-native-smtp-mailer#18]
`pod install` fails because `s.homepage` in `RNSmtpMailer.podspec` is missing a value.

> [!] The `RNSmtpMailer` pod failed to validate due to 1 error:
>     - ERROR | attributes: Missing required attribute `homepage`.
>     - WARN  | source: The version should be included in the Git tag.
>     - WARN  | description: The description is equal to the summary.

Also `s.source` and `s.author` should contain the correct information.

It's working when I change it to:
```
  s.homepage     = "https://github.com/angelos3lex/react-native-smtp-mailer"
```

See https://guides.cocoapods.org/syntax/podspec.html for required attributes.

**Comment by angelos3lex** [comment]
Thanks  a lot, its fixed on 1.2.0!
