### ISSUE TITLE
null is not an object (evaluating reactNativesmtpmailer.default.sendmail)

### ISSUE THREAD

**Issue by blueneel05** [angelos3lex/react-native-smtp-mailer#19]
I am getting error "null is not an object (evaluating reactNativesmtpmailer.default.sendmail)" when trying to send an email. I have used automatic linking. 

And when I follow the steps for manual linking and when I try to send an email I get error "'React/RCTDefines.h' file not found". 

Works fine on android. Only IOS part has issue
I am using RN 0.60. Any help ?

**Comment by blueneel05** [comment]
Anybody there ?

**Comment by blueneel05** [comment]
I solved this issue by renaming the import statement to `#import "rctdefines.h"` and searched for the file "rctdefines.h" from finder and adding the path of the file in header search path in RNSmtpMailer.a in Xcode.

**Comment by marciok** [comment]
Having the same issue here. @blueneel05 could you send a print of your code? 
Thanks

**Comment by marciok** [comment]
I found the source of the problem, it is on `RNSmtpMailer.podspec`. 
The source files are not being copied, the path "RNSmtpMailer/**/*.{h,m}" is wrong, it should be "*.{h,m}" since the files and Podspec are at the same location, plus the you have to add ` s.dependency "mailcore2-ios"` as a dependency. 

Podspec after fix:

```
Pod::Spec.new do |s|
  s.name         = "RNSmtpMailer"
  s.version      = "1.2.0"
  s.summary      = "RNSmtpMailer"
  s.description  = <<-DESC
                  RNSmtpMailer
                   DESC
  s.homepage     = "https://github.com/angelos3lex/react-native-smtp-mailer"
  s.license      = "MIT"
  s.author       = { "author" => "angelos3lex" }
  s.platform     = :ios, "7.0"
  s.source       = { :git => "https://github.com/angelos3lex/react-native-smtp-mailer.git", :tag => "master" }
  
  s.source_files  = "*.{h,m}"

  s.requires_arc = true

  s.dependency "React"
  s.dependency "mailcore2-ios"

end
```

**Comment by dionisio28** [comment]
Hi @marciok, I was with the same error, I made the changes RNSmtpMailer.podspec and then run pod install, right after that this mistake stopped and another started.
Error:

> 
> Apple Mach-O Linker Error Group
> no such file or directory: '/Users/acount/Library/Developer/Xcode/DerivedData/projectName-eehtedkfxgdaxhadldecpbhgjelx/Build/Products/Debug-iphonesimulator/libRNSmtpMailer.a'
>

**Comment by marciok** [comment]
First make sure that the files are being copied (pod is installed) RNSmtpMailer.h and RNSmtpMailer.m:
![Screen Shot 2019-09-27 at 15 25 56](https://user-images.githubusercontent.com/311156/65792941-2b763d00-e13b-11e9-9f43-8f1de3266a60.png)

Clean your build on Xcode and try again

**Comment by dionisio28** [comment]
@marciok  Thank you that was my problem, but I have a question
Does this api work on the ios emulator?

**Comment by marciok** [comment]
@dionisio28 yes!

**Comment by dionisio28** [comment]
Hi again @marciok, I went back to work on the mailing project now, so I reinstalled the library in _version 1.2.1_, changed the path in _RNSmtpMailer.podspec_ and added _"mailcore2-ios"_ OK the project compiled, however when sending email it takes a while and soon after catch falls :(.
![Captura de Tela 2019-10-10 às 09 08 34](https://user-images.githubusercontent.com/48914458/66574359-15f11200-eb42-11e9-8b6d-b79dee7ae726.png)

**Comment by marciok** [comment]
@dionisio28 It looks like a problem with your SMTP server, check the credentials.
