### ISSUE TITLE
Some emails are not sent on iOS

### ISSUE THREAD

**Issue by mattroa** [angelos3lex/react-native-smtp-mailer#24]
While sending emails, some emails go through and some don't. Is there a limit on using this package? Like, how many emails can be sent per hour or day? Is there a need for an upgrade or something?

**Comment by angelos3lex** [comment]
I haven't encountered such a problem, though i haven't stress-test it. This library is a RN bridge for android javamail and ios mailcore2. If there is such a limitation maybe there is on any the native libraries?
But, my guess is that this limitation is made by your provider. Do you encounter this problem using your own smtp server which has no limitations?

**Comment by mattroa** [comment]
I've just followed your steps here and surely it's working. Unsent emails happened on production but when on development, I can't seem to encounter any errors. So I guess I'll do some further testing and recheck some functions. Thanks for the reply.
