### ISSUE TITLE
Amazon AWS iOS unstable connection

### ISSUE THREAD

**Issue by LuizFBrisighello** [angelos3lex/react-native-smtp-mailer#31]
```
    RNSmtpMailer.sendMail({
      mailhost: 'email-smtp.us-east-1.amazonaws.com',
      port: '587',
      ssl: false,
      username: 'host.user',
      password: 'host.password',
      from: 'auth.mail@mail.com',
      recipients: 'my.mail@mail.com',
      subject: 'subject',
      htmlBody: '<h1>header</h1><p>body</p>',
      attachmentPaths: [],
      attachmentNames: [],
      attachmentTypes: []
    })
      .then(success => console.log(success))
      .catch(err => console.log(err))
```

On `iOS`:
`Error: A stable connection to the server could not be stablished`

I'm having trouble to debug these. I'm not the adming of the AWS account wich it makes even harder.
Does anyone have a guess?

`react-native: 0.60.5`
`react-native-smtp-mailer: 1.2.2`

**Comment by NikonovichN** [comment]
@angelos3lex, @MarkusPettersson98 
Any clues?

**Comment by LuizFBrisighello** [comment]
@NikonovichN I ended up never solving/working around this and abandoned the lib. My co-worker did every thing on the backend with a simple rest API
