### ISSUE TITLE
How can I add base64 string in attachment?

### ISSUE THREAD

**Issue by niharikaprasad** [angelos3lex/react-native-smtp-mailer#34]

**Comment by angelos3lex** [comment]
Store it in a .txt file and send that?
You can always send it in the body of the message as well

**Comment by niharikaprasad** [comment]
> Store it in a .txt file and send that?
> You can always send it in the body of the message as well

I mean to attach a pdf file which is being generated in my React Code using jsPDF (https://github.com/MrRio/jsPDF).
I want send the generated file to the user.

**Comment by angelos3lex** [comment]
This lib creates a normal .pdf file no?
You can send that file normally like all other file types, by specifying its path
