### ISSUE TITLE
MailCore.h import problem on case sensitive runner

### ISSUE THREAD

**Issue by Reloflex** [angelos3lex/react-native-smtp-mailer#35]
Building the package on a case sensitive runner fails with the error:

`'Mailcore/Mailcore.h' file not found.`

Solution (I will create a PR):  

**ios/RNSmtpMailer.m on line 4:**

Instead of:  
`#import <Mailcore/Mailcore.h>`

There should be:  
`#import <MailCore/MailCore.h>`

**Comment by angelos3lex** [comment]
v1.2.3 includes this fix
