### ISSUE TITLE
Sending messages is not allowed on this server

### ISSUE THREAD

**Issue by stefandbd** [angelos3lex/react-native-smtp-mailer#38]
Posting this issue here for anyone who has difficulties with it. Pay attention to 2 things:

- from: "", 

  // here to have a correct smtp server configured. Even if it is just a string, and you might think that it doesn't matter from who is the email coming, it will give you that error. (eg: you can use same server as you have for username)

- For iOS add all:   

attachmentPaths: [],
attachmentNames: [],
attachmentTypes: [], 

otherwise, the same error might happen.

Feel free to close the issue, it is just a solution for whomever needs it 👍

**Comment by angelos3lex** [comment]
Thanks! 
For the first bullet, i sometime need to update the docs to make much more clear what are the required fields and what's their purpose.
For the second bullet, the lib needs a refactor in some point, to not need these fields if someone doesn't want to attach files. It's just some more `if` additions that are missing on the bridges. 
Hopefully i'll go into these when the time allows
