### ISSUE TITLE
Username and Password Not Accepted

### ISSUE THREAD

**Issue by YudeMgoy** [angelos3lex/react-native-smtp-mailer#40]
i get this error even my username and password are match [Error: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials g67sm1422389pfb.9 - gsmtp]

**Comment by angelos3lex** [comment]
You nee to configure your google smtp to allow access from less secure apps to successfully send emails. Check [this](https://support.google.com/mail/thread/5621336?hl=en)
