### ISSUE TITLE
release build failed on Android

### ISSUE THREAD

**Issue by sandeepsharma27** [angelos3lex/react-native-smtp-mailer#5]
here is my output

             E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-nl_values-nl.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-pa_values-pa.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-pl_values-pl.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-port_values-port.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-pt-rBR_values-pt-rBR.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-pt-rPT_values-pt-rPT.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-pt_values-pt.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-ro_values-ro.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-ru_values-ru.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-si_values-si.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-sk_values-sk.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-sl_values-sl.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-sq_values-sq.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-sr_values-sr.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-sv_values-sv.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-sw600dp-v13_values-sw600dp-v13.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-sw_values-sw.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-ta_values-ta.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-te_values-te.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-th_values-th.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-tl_values-tl.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-tr_values-tr.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-uk_values-uk.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-ur_values-ur.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-uz_values-uz.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-v16_values-v16.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-v17_values-v17.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-v18_values-v18.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-v21_values-v21.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-v22_values-v22.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-v23_values-v23.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-v24_values-v24.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-v25_values-v25.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-v26_values-v26.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-vi_values-vi.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-watch-v20_values-watch-v20.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-xlarge-v4_values-xlarge-v4.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-zh-rCN_values-zh-rCN.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-zh-rHK_values-zh-rHK.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-zh-rTW_values-zh-rTW.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values-zu_values-zu.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\values_values.arsc.flat\
          -R\
          E:\LSQ\node_modules\react-native-smtp-mailer\android\build\intermediates\res\compiled\release\xml_preferences.xml.flat\
          --auto-add-overlay\
          --non-final-ids\
          -0\
          apk\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 14s
182 actionable tasks: 4 executed, 178 up-to-date

**Comment by sandeepsharma27** [comment]
My Build.gradle


```
buildscript {
    ext {
         buildToolsVersion = "28.0.2"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:4.2.0'

      
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}


task wrapper(type: Wrapper) {
     gradleVersion = '4.6'
    distributionUrl = distributionUrl.replace("bin", "all")
}

```


 React Native Environment Info:
  ```
  System:
      OS: Windows 8.1
      CPU: (4) x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
      Memory: 1.42 GB / 7.88 GB
    Binaries:
      Yarn: 1.12.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
```

**Comment by angelos3lex** [comment]
Thanks for posting, updates were required. Try with v1.1.10 that was just published and let me know if its resolved!

**Comment by sandeepsharma27** [comment]
Sounds good
Thanks

**Comment by sandeepsharma27** [comment]
yes, it is resolved now
