### ISSUE TITLE
Library works only in debug mode, not in release mode

### ISSUE THREAD

**Issue by fanatic75** [angelos3lex/react-native-smtp-mailer#8]
It shows error : smtp in the catch function in release build. Works fine when I'm trying this on debug mode.

**Comment by angelos3lex** [comment]
In which platform, which RN version and which react-native-smtp-mailer version?
Can you also open android logcat and see the error there for more info?

**Comment by fanatic75** [comment]
my code was building fine into release mode until I added this module in my react native project.
Now I get some warning from proguardrelease, so I added -ignorewarnings into my progurard rules file and it builds fine now. But it shows me error:smtp in the catch function whenever I send the mail.

**Comment by fanatic75** [comment]
Also in the manual installation for android, 
you have written to add changes to the file MainActivity.Java, shouldn't it be MainApplication.java? Because the things you're telling us to add are in MainApplication.java
for eg : getPackages() is in MainApplication.java and I have added new RNSmtpMailerPackage() under asList

**Comment by fanatic75** [comment]
Okay so I fixed this issue by removing proguard from the application and then building it again. But I really want the proguard to keep my application size smaller and safer. 
I'll post my release log file. Can you please tell me how should I fix those warnings which I'm getting when proguard is enabled and minifyEnabled is true and shrinkResources is true too.

**Comment by angelos3lex** [comment]
Unfortunately i have no experience with proguard flow...  
Could you post the warnings that reference this library?
Also could you post the error through android logcat? (Not the catch on js side, but through the logcat on android studio)

**Comment by angelos3lex** [comment]
Probably is because of not including the jars on the proguard file needed for this lib to work.
Instead of ignore warnings, try using:
`-libraryjars 'path/to/jar'`
Below are three jars this lib is using:
path/to/here/node_modules/react-native-smtp-mailer/android/libs/additionnal.jar
path/to/here/node_modules/react-native-smtp-mailer/android/libs/android-activation-1.6.0.jar
path/to/here/node_modules/react-native-smtp-mailer/android/libs/android-mail-1.6.0.jar

**Comment by fanatic75** [comment]
So you don't  enable Proguard for your android apps?

**Comment by angelos3lex** [comment]
Happy news i found the solution here,
add to your proguard file the following:
```
-dontshrink 
-keep class javax.** {*;} 
-keep class com.sun.** {*;} 
-keep class myjava.** {*;} 
-keep class org.apache.harmony.** {*;} 
-dontwarn java.awt.** 
-dontwarn java.beans.Beans 
-dontwarn javax.security.** 
-dontwarn javax.activation.** 
```

**Comment by fanatic75** [comment]
It worked. Thanks mate! 
Also I didn't use -dontshrink either. 
Will put up a merge request by adding in the documentation.
