### ISSUE TITLE
cannot read property 'sendMail' of undefined

### ISSUE THREAD

**Issue by KevvinG** [angelos3lex/react-native-smtp-mailer#9]
I have been running into this issue.  I'm quite new to react-native so I may be missing something.

I used npm to install and followed the extra steps and installed the podfile.

And of course I am importing at the top of my file

Implementation below, any help would be appreciated!

sendEmail = () => {
      RNSmtpMailer.sendMail({
          mailhost: "smtp.gmail.com",
          port: "465",
          ssl: true,
          username: "circuitlab.the@gmail.com",
          password: "****",
          recipients:"kevingrzela@yahoo.com",
          subject:"test",
          htmlBody:"<p>"+"foo"+"</p>",
          attachmentPaths: [],
          attachmentNames: [],
          attachmentTypes: []
      })
      .then(success=>{
          // this.setState({loading:false});
          alert("Message sent successfully. We will respond you within next 2 working days. Thank you for your patience.");
      })
      .catch(err=>{
          // this.setState({loading:false});
          alert("Could not send message due to some error. Please contact us through our helpline Number. "+err);
      });
}

**Comment by dineshlt** [comment]
Hi @KevvinG 

  I am also having to face that same issue. Why you have closed this ticket. If you have fixed it kindly help me how can I fix this issue?

**Comment by weslei-dias-vakt** [comment]
Same here
